
IF EXISTS(
SELECT TABLE_NAME, COLUMN_NAME 
		FROM INFORMATION_SCHEMA.COLUMNS
		where TABLE_NAME = 'AG_ExportData0062' 
		AND COLUMN_NAME = 'firmado')
BEGIN 
		ALTER TABLE dbo.AG_ExportData0062 DROP COLUMN firmado
END		 
GO	


IF NOT EXISTS (SELECT TABLE_NAME, COLUMN_NAME 
		FROM INFORMATION_SCHEMA.COLUMNS
		where TABLE_NAME = 'AG_ExportData0062' 
		AND COLUMN_NAME = 'FechaOpenFilePdf')
BEGIN

		ALTER TABLE dbo.AG_ExportData0062 ADD FechaOpenFilePdf DATETIME 

END 
GO		


IF NOT EXISTS (SELECT TABLE_NAME, COLUMN_NAME 
		FROM INFORMATION_SCHEMA.COLUMNS
		where TABLE_NAME = 'AG_ExportData0062' 
		AND COLUMN_NAME = 'Estado')
BEGIN

		ALTER TABLE dbo.AG_ExportData0062 ADD Estado bit 

END 
GO		




